services:
  therefore-pipeline:
    image: fybre/thereforeembedder
    container_name: thereforeembedder
    restart: unless-stopped
    environment:
      - TENANT_ARG=mytenant # optional
      - PAUSE_INTERVAL=3h # optional
    volumes:
      - ./config:/app/config # ensure leading slash in container path!
      - ./db:/app/db # persists both docs and vectordb directories
